name: Check build
on:
  push:
    branches: [main, stage]
  pull_request:
    types: [opened, reopened, synchronize, closed]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build
        working-directory: .
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          yarn build:prod

      - name: Fail if unstashed changes exists
        run: |
          ! git status -s | grep -E '^ M '
